# Fase de construcción
FROM node:20-alpine AS builder

# Instalar pnpm
RUN npm install -g pnpm

# Establecer el directorio de trabajo en la aplicación
WORKDIR /app

# Copiar el contenido actual (excepto lo que esté en el archivo .dockerignore)
COPY . .

# Instalación de las dependencias de node con pnpm
RUN pnpm install

# Expone el puerto para el desarrollo (puerto de la aplicación Angular)
EXPOSE 4200

# Comando para iniciar la aplicación en modo de desarrollo
CMD ["pnpm", "start"]
