version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
